services:
  # Serviço de Agricultores (com upload de arquivos integrado)
  farmer-service:
    build:
      context: ./farmer-service
      dockerfile: Dockerfile
    container_name: farm-investment-farmer-service
    environment:
      - NODE_ENV=development
      - PORT=3001
      - DATABASE_URL=${DATABASE_URL}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - SUPABASE_STORAGE_BUCKET=${SUPABASE_STORAGE_BUCKET}
      - SUPABASE_STORAGE_ENDPOINT=${SUPABASE_STORAGE_ENDPOINT}
      - SUPABASE_STORAGE_REGION=${SUPABASE_STORAGE_REGION}
      - SUPABASE_STORAGE_ACCESS_KEY_ID=${SUPABASE_STORAGE_ACCESS_KEY_ID}
      - SUPABASE_STORAGE_SECRET_ACCESS_KEY=${SUPABASE_STORAGE_SECRET_ACCESS_KEY}
    ports:
      - "3001:3001"
    networks:
      - farm-investment-network

  # Serviço de Investidores
  investor-service:
    build:
      context: ./investor-service
      dockerfile: Dockerfile
    container_name: farm-investment-investor-service
    environment:
      - NODE_ENV=development
      - PORT=3002
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "3002:3002"
    networks:
      - farm-investment-network

  # Serviço de Notificações
  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    container_name: farm-investment-notification-service
    environment:
      - NODE_ENV=development
      - PORT=3003
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - EMAIL_PROVIDER=${EMAIL_PROVIDER:-ethereal}
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      - GMAIL_USER=${GMAIL_USER}
      - GMAIL_APP_PASSWORD=${GMAIL_APP_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
    ports:
      - "3003:3003"
    networks:
      - farm-investment-network

networks:
  farm-investment-network:
    driver: bridge
